version: 0.2
    
phases:
  install:
    commands:
      - python -m venv venv
      - source venv/bin/activate
      - echo Installing requirements from file
      - pip install pytest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started today
      - echo Building and running tests
      - pytest tests/unit/test_factorial.py -v
  post_build:
    commands:
      - echo Build completed on `date`  
