version: 0.2
    
phases:
  install:
    commands:
      - echo Installing requirements from file
      - pip install pytest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started today
      - echo Building and running tests
      - python tests/unit/test_factorial.py
  post_build:
    commands:
      - echo Build completed on `date`  
